### ISSUE TITLE
ddb-aio still being generated on hub.docker?

### ISSUE THREAD

**Issue by rdzimmer** [dalmatinerdb/docker-aio#1]
Hi,

I'm trying Dalmatinerdb for the first time and was looking to use the docker images.  I am getting a 404 for the ddb-aio image.  Nothing comes up for it when I search hub.docker.com.  I was able to download the individual images ok (ddb, dfe etc).  I'm still reading up on how to get them to work together, so an all in one package like the "aio" would be great if its still out there somewhere.  Thanks!

**Comment by Licenser** [comment]
This is replaced by: https://github.com/dalmatinerdb/docker-ddb-compose

which also includes a grafana as a added bonus :)

**Comment by rdzimmer** [comment]
Thanks!
