### ISSUE TITLE
postgresql-9.5 not found

### ISSUE THREAD

**Issue by georgekrueger** [dalmatinerdb/docker-aio#2]
....
Reading state information...
E: Version '9.5.5-1.pgdg80+1' for 'postgresql-9.5' was not found
E: Version '9.5.5-1.pgdg80+1' for 'postgresql-contrib-9.5' was not found
The command '/bin/sh -c apt-get update  && apt-get install -y postgresql-common         && sed -ri 's/#(create_main_cluster) .*$/\1 = false/' /etc/postgresql-common/createcluster.conf       && apt-get install -y           postgresql-$PG_MAJOR=$PG_VERSION                postgresql-contrib-$PG_MAJOR=$PG_VERSION      && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by Licenser** [comment]
Hi this is no longer maintained we split the components and provide: https://github.com/dalmatinerdb/docker-ddb-compose
